### ISSUE TITLE
Regression on behaviour fields

### ISSUE THREAD

**Issue by atiro** [digirati-co-uk/vam-viewer#53]
Previously behaviour fields were drop-downs, like so:

![screenshot-2020-09-17-12:12:59](https://user-images.githubusercontent.com/9074093/93764423-fcd65980-fc0a-11ea-984d-1ad8465f3d44.png)

 they are now text fields which have to have the behaviours typed in exactly.

**Comment by patrickpatrickpatrick** [comment]
w/ the config now working, this has been fixed
